#Especies de animais
INSERT INTO `especie` (`id`, `nome`) VALUES (1, 'Cachorro');
INSERT INTO `especie` (`id`, `nome`) VALUES (2, 'Gato');

#Racas de animais

#Caes
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Afegão Hound', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Affenpinscher', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Airedale Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Akita', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('American Staffordshire Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Basenji', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Basset Hound', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Beagle', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Beagle Harrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bearded Collie', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bedlington Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bichon Frisé', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bloodhound', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bobtail', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Boiadeiro Australiano', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Boiadeiro Bernês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Border Collie', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Border Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Borzoi', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Boston Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Boxer', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Buldogue Francês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Buldogue Inglês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bull Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bulmastife', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cairn Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cane Corso', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cão de Água Português', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cão de Crista Chinês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cavalier King Charles Spaniel', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Chesapeake Bay Retriever', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Chihuahua', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Chow Chow', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cocker Spaniel Americano', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cocker Spaniel Inglês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Collie', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Coton de Tuléar', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Dachshund', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Dálmata', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Dandie Dinmont Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Doberman', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Dogo Argentino', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Dogue Alemão', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Fila Brasileiro', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Fox Terrier (Pelo Duro e Pelo Liso)', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Foxhound Inglês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Galgo Escocês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Galgo Irlandês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Golden Retriever', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Grande Boiadeiro Suiço', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Greyhound', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Grifo da Bélgica', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Husky Siberiano', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Jack Russell Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('King Charles', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Komondor', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Labradoodle', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Labrador Retriever', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Lakeland Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Leonberger', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Lhasa Apso', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Lulu da Pomerânia', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Malamute do Alasca', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Maltês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Mastife', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Mastim Napolitano', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Mastim Tibetano', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Norfolk Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Norwich Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Papillon', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pastor Alemão', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pastor Australiano', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pinscher Miniatura', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Poodle', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pug', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Rottweiler', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Sem Raça Definida (SRD)', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('ShihTzu', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Silky Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Skye Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Staffordshire Bull Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Terra Nova', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Terrier Escocês', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Tosa', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Weimaraner', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Welsh Corgi (Cardigan)', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Welsh Corgi (Pembroke)', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('West Highland White Terrier', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Whippet', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Xoloitzcuintli', NULL, 1);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Yorkshire Terrier', NULL, 1);


#Gatos
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Abissínio', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Angorá', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Balinês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bengal', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Americano', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bobtail japonês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Bombay', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Burmês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Burmês vermelho', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Chartreux', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Colorpoint de Pêlo Curto', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cornish Rex', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Curl Americano', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Devon Rex', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Himalaio', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Javanês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Korat', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('LaPerm', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Maine Coon', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Manx', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Cymric', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Mau Egípcio', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Mist Australiano', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Munchkin', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Norueguês da Floresta', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pelo curto americano', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pelo curto brasileiro', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pelo curto europeu', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pelo curto inglês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Persa', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Pixie-bob', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Ragdoll', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Ocicat', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Russo Azul', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Sagrado da Birmânia', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Savannah', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Scottish Fold', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Selkirk Rex', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Sem Raça Definida (SRD)', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Siamês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Siberiano', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Singapura', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Somali', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Sphynx', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Thai', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Tonquinês', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Toyger', NULL, 2);
INSERT INTO `raca` (`nome`, `descricao`, `especie`) VALUES ('Usuri', NULL, 2);
